/**
 * Copy del checkout y del área del alumno. Igual que site.ts: los componentes
 * solo pintan, los textos se cambian acá.
 */
export const studentCopy = {
  checkout: {
    eyebrow: 'Pago seguro',
    title: 'Completa tu compra',
    loading: 'Cargando tu pedido…',
    notFound: 'No encontramos este producto.',
    notAvailable: 'Este producto no está a la venta en este momento.',
    backToProduct: 'Ver el producto',
    summaryTitle: 'Tu pedido',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    total: 'Total a pagar',
    lifetime: 'Acceso de por vida',
    accessDays: (days: number) => `Acceso por ${days} días`,
    types: {
      course: 'Curso',
      download: 'Descargable',
      service: 'Asesoría',
      free: 'Recurso gratuito',
    },
    coupon: {
      label: '¿Tienes un cupón?',
      placeholder: 'Código',
      apply: 'Aplicar',
      remove: 'Quitar',
      applied: (code: string, percent: number) =>
        `Cupón ${code} aplicado: ${percent}% de descuento`,
    },
    buyer: {
      title: 'Tus datos',
      hint: 'El procesador de pagos los pide para validar tu tarjeta. Los guardamos en tu cuenta para la próxima vez.',
      email: 'Correo de la cuenta',
      phone: 'Celular',
      phonePlaceholder: '0991234567',
      documentId: 'Cédula, RUC o pasaporte',
      documentPlaceholder: '0912345678',
      phoneError: 'Escribe un celular válido, por ejemplo 0991234567.',
      documentError: 'Escribe tu número de cédula (10 dígitos), RUC o pasaporte.',
    },
    confirm: 'Continuar al pago',
    confirmFree: 'Obtener acceso',
    creating: 'Preparando tu pago…',
    freeGranted: 'Listo, ya tienes acceso. Lo encuentras en Mis cursos.',
    pay: {
      title: 'Paga con tu tarjeta',
      secure: 'El pago se procesa con Payphone. No guardamos los datos de tu tarjeta.',
      loadingBox: 'Cargando el formulario de pago…',
      timer: 'Este formulario vence en',
      expiredTitle: 'El formulario de pago venció',
      expiredText:
        'Por seguridad cada intento dura 10 minutos. No se hizo ningún cobro; genera uno nuevo para continuar.',
      retry: 'Generar nuevo intento',
      errorTitle: 'No pudimos cargar el formulario de pago',
      errorText: 'Revisa tu conexión e inténtalo de nuevo. No se hizo ningún cobro.',
      edit: 'Cambiar mis datos o el cupón',
    },
    owned: {
      title: 'Ya tienes este producto',
      text: 'Tu acceso sigue vigente, no necesitas comprarlo otra vez.',
      cta: 'Ir a Mis cursos',
    },
  },

  response: {
    confirmingTitle: 'Estamos confirmando tu pago',
    confirmingText: 'No cierres ni recargues esta página. Toma solo unos segundos.',
    paidEyebrow: 'Pago aprobado',
    paidTitle: 'Gracias por tu compra',
    paidText: (title: string) =>
      `Ya tienes acceso a ${title}. También te enviamos la confirmación por correo.`,
    paidCourseCta: 'Empezar ahora',
    paidDownloadCta: 'Ir a Mis cursos',
    paidServiceText:
      'Kath te escribirá para coordinar tus sesiones. Revisa tu correo y tu WhatsApp.',
    paidServiceCta: 'Volver al inicio',
    canceledTitle: 'Cancelaste el pago',
    canceledText: 'No se hizo ningún cobro. Puedes intentarlo otra vez cuando quieras.',
    failedTitle: 'No pudimos confirmar tu pago',
    failedText:
      'Si tu banco te notificó un cobro, se reversa automáticamente. Puedes intentarlo otra vez.',
    retry: 'Intentar de nuevo',
    missingTitle: 'Este enlace no es válido',
    missingText: 'No recibimos los datos del pago. Si acabas de pagar, revisa Mis cursos.',
    loginTitle: 'Inicia sesión para confirmar tu pago',
    loginText: 'Tu sesión expiró. Ingresa y confirmamos el pago de inmediato.',
    loginCta: 'Iniciar sesión',
    orderTotal: 'Total pagado',
    myCourses: 'Ir a Mis cursos',
    courses: 'Ver cursos',
  },

  myCourses: {
    eyebrow: 'Tu espacio',
    title: 'Mis cursos',
    greeting: (name: string) => `Hola, ${name}. Sigue donde lo dejaste.`,
    loading: 'Cargando tus cursos…',
    errorTitle: 'No pudimos cargar tus cursos',
    retry: 'Reintentar',
    emptyTitle: 'Todavía no tienes cursos',
    emptyText: 'Cuando compres un curso o una plantilla, aparecerá aquí.',
    emptyCta: 'Ver cursos',
    availableUntil: (date: string) => `Disponible hasta el ${date}`,
    expired: (date: string) => `Tu acceso venció el ${date}`,
    expiredNoDate: 'Tu acceso venció',
    revoked: 'Tu acceso fue desactivado',
    locked: 'Bloqueado',
    rebuy: 'Volver a comprar',
    start: 'Empezar',
    resume: 'Continuar',
    review: 'Repasar',
    download: 'Descargar',
    downloading: 'Preparando…',
    tutorial: 'Ver tutorial',
    progress: (done: number, total: number) => `${done} de ${total} clases`,
    serviceNote: 'Kath coordina tus sesiones por correo y WhatsApp.',
  },

  learn: {
    loading: 'Cargando tu curso…',
    back: 'Mis cursos',
    blockedTitle: 'No tienes acceso a este contenido',
    blockedText: 'Tu acceso venció o todavía no has comprado este producto.',
    blockedCta: 'Ver opciones de compra',
    notFoundTitle: 'No encontramos este curso',
    errorTitle: 'No pudimos cargar el curso',
    retry: 'Reintentar',
    emptyTitle: 'Las clases estarán disponibles pronto',
    emptyText: 'Te avisaremos por correo cuando se publiquen.',
    videoLoading: 'Cargando el video…',
    videoError: 'No pudimos cargar el video.',
    markDone: 'Marcar como vista',
    done: 'Clase vista',
    next: 'Siguiente clase',
    finished: 'Terminaste todas las clases. Bien hecho.',
    attachments: 'Material de la clase',
    syllabus: 'Temario',
    lessonsCount: (done: number, total: number) => `${done}/${total}`,
    download: 'Descargar archivo',
    live: {
      title: 'Clases en vivo',
      join: 'Unirme por Meet',
      recording: 'Ver la grabación',
      past: 'Finalizada',
      upcoming: 'Próxima',
    },
  },
} as const
