/**
 * Copy del checkout y del área del alumno. Igual que site.ts: los componentes
 * solo pintan, los textos se cambian acá.
 */
export const studentCopy = {
  checkout: {
    eyebrow: 'Pago seguro',
    title: 'Completa tu compra',
    loading: 'Cargando tu pedido…',
    notFound: 'No encontramos este producto.',
    notAvailable: 'Este producto no está a la venta en este momento.',
    backToProduct: 'Ver el producto',
    summaryTitle: 'Tu pedido',
    subtotal: 'Subtotal',
    discount: 'Descuento',
    total: 'Total a pagar',
    lifetime: 'Acceso de por vida',
    accessDays: (days: number) => `Acceso por ${days} días`,
    types: {
      course: 'Curso',
      download: 'Descargable',
      service: 'Asesoría',
      free: 'Recurso gratuito',
    },
    coupon: {
      label: '¿Tienes un cupón?',
      codeLabel: 'Código del cupón',
      placeholder: 'Código',
      apply: 'Aplicar',
      remove: 'Quitar',
      applied: (code: string, percent: number) =>
        `Cupón ${code} aplicado: ${percent}% de descuento`,
    },
    steps: {
      label: 'Pasos de tu compra',
      data: 'Tus datos',
      pay: 'Pago',
    },
    identity: {
      title: 'Tus datos',
      registerHint:
        'Con estos datos creamos tu cuenta, para que entres a tu compra cuando quieras.',
      name: 'Nombre y apellido',
      email: 'Correo',
      emailHint: 'Aquí te llega tu acceso.',
      phone: 'Celular',
      phonePlaceholder: '0991234567',
      documentId: 'Cédula, RUC o pasaporte',
      documentPlaceholder: '0912345678',
      documentHint: 'La pide Payphone para validar tu pago.',
      usePassport: 'Tengo pasaporte (con letras)',
      newPassword: 'Crea una contraseña',
      newPasswordHint: 'Mínimo 8 caracteres. Con ella entras después a tu compra.',
      password: 'Contraseña',
      haveAccount: 'Ya tengo cuenta',
      noAccount: 'No tengo cuenta, quiero crearla',
      loginTitle: 'Entra a tu cuenta',
      loginHint: 'Escribe tu correo y tu contraseña, y sigues con el pago aquí mismo.',
      forgot: 'Olvidé mi contraseña',
      exists: 'Ya tienes una cuenta con este correo. Escribe tu contraseña para continuar.',
      profileHint: 'Solo nos falta esto para preparar tu pago. Lo guardamos en tu cuenta.',
      edit: 'Editar',
      requestHint: (email: string) =>
        `Usa el mismo correo con el que enviaste tu solicitud: ${email}.`,
      requestMismatch: (email: string) =>
        `Esta solicitud se envió con el correo ${email}. Para pagarla tienes que entrar con ese mismo correo.`,
      requestSwitch: 'Entrar con ese correo',
      errors: {
        name: 'Escribe tu nombre y apellido.',
        email: 'Revisa tu correo, parece que le falta algo. Ejemplo: nombre@gmail.com',
        phone: 'Tu celular debe tener 10 dígitos y empezar con 09. Ejemplo: 0991234567',
        documentId:
          'Tu cédula tiene 10 dígitos (el RUC, 13). Si no tienes, escribe tu número de pasaporte.',
        newPassword: 'Tu contraseña necesita al menos 8 caracteres.',
        password: 'Escribe tu contraseña.',
      },
    },
    trust: {
      label: 'Compra segura',
      secure: 'Pago seguro con Payphone',
      instant: 'Acceso inmediato',
      service: 'Kath te escribe apenas pagas',
      methods: 'Aceptamos tarjeta de crédito, tarjeta de débito y Payphone.',
    },
    requestInvalid: {
      title: 'Este enlace de pago ya no está activo',
      text: 'Si ya pagaste, revisa tu correo. Si no, escríbeme y te envío un enlace nuevo.',
    },
    confirm: 'Continuar al pago',
    confirmFree: 'Obtener acceso',
    signingIn: 'Guardando tus datos…',
    creating: 'Preparando tu pago…',
    freeGranted: 'Listo, ya tienes acceso. Lo encuentras en Mis cursos.',
    pay: {
      title: 'Paga con tu tarjeta',
      secure: 'El pago se procesa con Payphone. No guardamos los datos de tu tarjeta.',
      loadingBox: 'Cargando el formulario de pago…',
      timer: 'Este formulario vence en',
      expiredTitle: 'El formulario de pago venció',
      expiredText:
        'Por seguridad cada intento dura 10 minutos. No se hizo ningún cobro; genera uno nuevo para continuar.',
      retry: 'Generar nuevo intento',
      errorTitle: 'No pudimos cargar el formulario de pago',
      errorText: 'Revisa tu conexión e inténtalo de nuevo. No se hizo ningún cobro.',
      edit: 'Cambiar mis datos o el cupón',
    },
    owned: {
      title: 'Ya tienes este producto',
      text: 'Tu acceso sigue vigente, no necesitas comprarlo otra vez.',
      cta: 'Ir a Mis cursos',
    },
  },

  response: {
    confirmingTitle: 'Estamos confirmando tu pago',
    confirmingText: 'No cierres ni recargues esta página. Toma solo unos segundos.',
    paidEyebrow: 'Pago aprobado',
    paidTitle: 'Gracias por tu compra',
    paidText: (title: string) => `Ya tienes acceso a ${title}.`,
    emailSent: 'Te enviamos un correo con tu acceso.',
    emailSentService: 'Te enviamos un correo con la confirmación de tu pago.',
    paidCourseCta: 'Ir a mi curso',
    paidDownloadCta: 'Descargar mi plantilla',
    paidDownloading: 'Preparando tu descarga…',
    paidTutorialCta: 'Ver el tutorial',
    paidServiceText:
      'Kath te escribirá para coordinar tus sesiones. Revisa tu correo y tu WhatsApp.',
    paidServiceCta: 'Volver al inicio',
    canceledTitle: 'Cancelaste el pago',
    canceledText:
      'No se hizo ningún cobro. Tus datos siguen guardados: inténtalo otra vez cuando quieras.',
    failedTitle: 'No pudimos confirmar tu pago',
    failedText:
      'Si tu banco te avisó de un cobro, se devuelve solo. Tus datos siguen guardados para intentarlo otra vez.',
    retry: 'Intentar de nuevo',
    missingTitle: 'Este enlace no es válido',
    missingText: 'No recibimos los datos del pago. Si acabas de pagar, revisa Mis cursos.',
    loginTitle: 'Inicia sesión para confirmar tu pago',
    loginText: 'Tu sesión expiró. Ingresa y confirmamos el pago de inmediato.',
    loginCta: 'Iniciar sesión',
    orderTotal: 'Total pagado',
    myCourses: 'Ir a Mis cursos',
    courses: 'Ver cursos',
  },

  myCourses: {
    eyebrow: 'Tu espacio',
    title: 'Mis cursos',
    greeting: (name: string) => `Hola, ${name}. Sigue donde lo dejaste.`,
    loading: 'Cargando tus cursos…',
    errorTitle: 'No pudimos cargar tus cursos',
    retry: 'Reintentar',
    emptyTitle: 'Todavía no tienes cursos',
    emptyText: 'Cuando compres un curso o una plantilla, aparecerá aquí.',
    emptyCta: 'Ver cursos',
    availableUntil: (date: string) => `Disponible hasta el ${date}`,
    expired: (date: string) => `Tu acceso venció el ${date}`,
    expiredNoDate: 'Tu acceso venció',
    revoked: 'Tu acceso fue desactivado',
    locked: 'Bloqueado',
    rebuy: 'Volver a comprar',
    start: 'Empezar',
    resume: 'Continuar',
    review: 'Repasar',
    download: 'Descargar',
    downloading: 'Preparando…',
    tutorial: 'Ver tutorial',
    progress: (done: number, total: number) => `${done} de ${total} clases`,
    serviceNote: 'Kath coordina tus sesiones por correo y WhatsApp.',
    comingSoon: 'Las clases se publican pronto. Te aviso por correo apenas estén.',
    enter: 'Entrar al curso',
  },

  learn: {
    loading: 'Cargando tu curso…',
    back: 'Mis cursos',
    blockedTitle: 'No tienes acceso a este contenido',
    blockedText: 'Tu acceso venció o todavía no has comprado este producto.',
    blockedCta: 'Ver opciones de compra',
    notFoundTitle: 'No encontramos este curso',
    errorTitle: 'No pudimos cargar el curso',
    retry: 'Reintentar',
    emptyTitle: 'Las clases estarán disponibles pronto',
    emptyText: 'Te avisaremos por correo cuando se publiquen.',
    videoLoading: 'Cargando el video…',
    videoError: 'No pudimos cargar el video.',
    markDone: 'Marcar como vista',
    done: 'Clase vista',
    next: 'Siguiente clase',
    finished: 'Terminaste todas las clases. Bien hecho.',
    attachments: 'Material de la clase',
    syllabus: 'Temario',
    lessonsCount: (done: number, total: number) => `${done}/${total}`,
    download: 'Descargar archivo',
    live: {
      title: 'Clases en vivo',
      join: 'Unirme por Meet',
      recording: 'Ver la grabación',
      past: 'Finalizada',
      upcoming: 'Próxima',
    },
  },
} as const
